import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

// ─────────────────────────────────────────────────────────────────────────────
// SECRET KEY — change this to invalidate all old codes and start fresh.
// Must match the SECRET_KEY in mac-academy-web/code-generator.html exactly.
// Keep this private — do not share it with students.
// ─────────────────────────────────────────────────────────────────────────────
const SECRET_KEY = "X8K2";

// A valid code looks like:  MAC-XXXX-X8K2
// The last 4 characters must match SECRET_KEY exactly (case-insensitive).
// The middle 4 characters are random — generated by the admin tool.
function isValidCode(raw: string): boolean {
  const code = raw.trim().toUpperCase();
  // Must match format MAC-{4 chars}-{SECRET_KEY}
  const expected = `MAC-XXXX-${SECRET_KEY}`.length;
  if (code.length !== expected) return false;
  if (!code.startsWith("MAC-")) return false;
  if (code[8] !== "-") return false;
  const suffix = code.slice(9); // last 4 chars
  return suffix === SECRET_KEY.toUpperCase();
}

interface ProContextType {
  isPro: boolean;
  unlockPro: (code: string) => boolean;
}

const ProContext = createContext<ProContextType | undefined>(undefined);

const PRO_KEY = "@mac_academy_pro";

export function ProProvider({ children }: { children: ReactNode }) {
  const [isPro, setIsPro] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const saved = await AsyncStorage.getItem(PRO_KEY);
        if (saved === "true") setIsPro(true);
      } catch {}
    })();
  }, []);

  const unlockPro = (code: string): boolean => {
    const valid = isValidCode(code);
    if (valid) {
      setIsPro(true);
      AsyncStorage.setItem(PRO_KEY, "true").catch(() => {});
    }
    return valid;
  };

  return (
    <ProContext.Provider value={{ isPro, unlockPro }}>
      {children}
    </ProContext.Provider>
  );
}

export function usePro() {
  const ctx = useContext(ProContext);
  if (!ctx) throw new Error("usePro must be used within ProProvider");
  return ctx;
}
