const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#FF6B1A",
    background: "#F8F9FA",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#FF6B1A",
    primaryForeground: "#ffffff",
    secondary: "#E8F4FD",
    secondaryForeground: "#1a1a2e",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#FF6B1A",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    surface: "#ffffff",
    surfaceElevated: "#f9f9f9",
    progressTrack: "#e5e5e5",
    progressFill: "#FF6B1A",
    locked: "#9ca3af",
    completed: "#22c55e",
    gold: "#FBBF24",
  },
  dark: {
    text: "#f0f0f0",
    tint: "#FF6B1A",
    background: "#0d0d0d",
    foreground: "#f0f0f0",
    card: "#1a1a1a",
    cardForeground: "#f0f0f0",
    primary: "#FF6B1A",
    primaryForeground: "#ffffff",
    secondary: "#1a1a2e",
    secondaryForeground: "#e2e8f0",
    muted: "#1a1a1a",
    mutedForeground: "#8a8a8a",
    accent: "#FF6B1A",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
    surface: "#1a1a1a",
    surfaceElevated: "#242424",
    progressTrack: "#2a2a2a",
    progressFill: "#FF6B1A",
    locked: "#4b5563",
    completed: "#22c55e",
    gold: "#FBBF24",
  },
  radius: 12,
};

export default colors;
